//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanielsCANSEntities : DbContext
    {
        public DanielsCANSEntities()
            : base("name=DanielsCANSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ASSESSMENT> ASSESSMENTS { get; set; }
        public virtual DbSet<CANS_ITEMS> CANS_ITEMS { get; set; }
        public virtual DbSet<ITEM_SCORE> ITEM_SCORE { get; set; }
        public virtual DbSet<PATIENT> PATIENTS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
    }
}
