//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANS_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANS_ITEMS()
        {
            this.ITEM_SCORE = new HashSet<ITEM_SCORE>();
            this.CANS_ITEMS1 = new HashSet<CANS_ITEMS>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ParentItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_SCORE> ITEM_SCORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANS_ITEMS> CANS_ITEMS1 { get; set; }
        public virtual CANS_ITEMS CANS_ITEMS2 { get; set; }
    }
}
